### ISSUE TITLE
Image missing in README.md when importing source connector from Helloid.

### ISSUE THREAD

**Issue by patrickhoryn** [Tools4everBV/HelloID-Conn-Prov-Source-PowerSchool-SIS-Students#11]
In the README.md file there is a linked image : "(assets/[Your-Image.jpg])".
When you use Helloid to import this connector, this image is not seen because Helloid enivrement is different then Github.
So the image link should be an absolute URIL : like 
"(https://github.com/Tools4everBV/[Connector-name]/blob/main/assets/[Your-Image.jpg])".

**Comment by JeroenBL** [comment]
Fixed in readme.
